spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Act@1234
    url: jdbc:mysql://localhost:3306/dell
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  banner:
    location: baner.txt
  github:
    api:
      token: MyGitHubTokenService
application:
  security:
    jwt:
      username: robel
      password:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha





